#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/bit_Adder.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/run_details/duse_master.tmp && \
mv /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/run_details/duse_master.tmp /DCNFS/users/student/sliu2/coen153/lab2/Adder/synopsys_custom/pvjob_lab6.bit_Adder.icv.lvs/run_details/duse_master
