ICV_HOME_DIR      = /opt/synopsys-2017/app/icvalidator/M-2017.06-1
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = lab6
INLIB_PATH        = 
OUTLIB            = run_details/bit_Adder
OUTLIB_PATH       = .
BLOCK             = bit_Adder
PYDB_PATH         = TOPCELLNAME_err
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS     =  HIERARCHICAL
FORMAT            = OPENACCESS
EVACCESS_PATH     = TOPCELLNAME_err
SCHEMATIC         = bit_Adder.sch_out
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.lvs.9m_saed90_lvs.lvs.rs
ENVIRONMENT STRING  SAED90_PDK = /opt/synopsys-2017/app/SAED/SAED_PDK90nm
EXTRACTION_FLOW   = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
WRITE_EQUIV_NETLISTS = ALL
