::sa::_backgroundSaeShell::signalProcessReady 1524612453
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::parentRunning
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/config/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession4 testbenchName default resultsDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal databaseName /DCNFS/users/student/sliu2/simulation/lab2/testbench_inverter/schematic/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::exit
